"""
Django settings for base_project project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bj(2%0ycp1nf0u*xq-k8p&)s7w^teu7@kc9yk(sepd26yqr4pg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'base_project',
    'interactive_challenges', # Register application module namespace
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'base_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # Fallback to local parameters if running locally outside of Kubernetes
        'NAME': os.environ.get('DB_NAME', 'oreilly_db'),
        'USER': os.environ.get('DB_USER', 'postgres_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'secure_password123'),
        # CRITICAL: Prioritize the cluster's service host string parameter
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'), 
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_PERSISTENT = True
CELERY_RESULT_EXPIRES = 1800

#To enable event push from celery to redis with 1 day cache expiry
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL',  'redis://127.0.0.1:6379/0')
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # for anonymous requests
        'rest_framework.throttling.UserRateThrottle', # for logged in user tokens
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '100/minute'
    }
}

LOGGING = { 
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'production_verbose': {
            'format': '[PLATFORM_METRICS_ENGINE] {levelname} {asctime} [{module}:{lineno}] -> {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console_stream': {
            'class': 'logging.StreamHandler',
            'formatter': 'production_verbose',
        },
    },
    'root': {
        'handlers': ['console_stream'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console_stream'],
            'level': 'ERROR', # Intercepts and formats application crashes cleanly
            'propagate': False,
        },
    },
}
